# Generated by Django 4.1.3 on 2025-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_vi_quan_ly', models.CharField(max_length=255)),
                ('loai_phuong_tien', models.CharField(max_length=255)),
                ('nhan_hieu', models.CharField(max_length=255)),
                ('nhan_hieu_sat_xi', models.CharField(max_length=255)),
                ('bien_kiem_soat', models.CharField(max_length=255)),
                ('nguyen_nhan_hu_hong', models.TextField()),
                ('bien_phap_thuc_hien', models.TextField()),
                ('ket_qua', models.CharField(max_length=255)),
            ],
        ),
    ]
