# Generated by Django 4.1.3 on 2025-12-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phuongtien',
            name='de_xuat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phuongtien',
            name='du_tru_kinh_phi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='phuongtien',
            name='nguoi_quan_ly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
