# Generated by Django 6.0 on 2026-01-03 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0002_phuongtien_de_xuat_phuongtien_du_tru_kinh_phi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danh_muc_nguon_cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mo_ta', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục nguồn cấp',
                'verbose_name_plural': 'Danh mục nguồn cấp',
            },
        ),
        migrations.AlterField(
            model_name='phuongtien',
            name='bien_phap_thuc_hien',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phuongtien',
            name='ket_qua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Chung_loai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=500, null=True, verbose_name='Tên')),
                ('maso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã số (Để trống để tự động tạo mã số)')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='qlpt.chung_loai', verbose_name='Nhóm chủng loại')),
            ],
            options={
                'verbose_name': 'Chủng loại',
                'verbose_name_plural': 'Chủng loại',
                'ordering': ['maso'],
            },
        ),
        migrations.CreateModel(
            name='Danh_muc_kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='qlpt.danh_muc_kho', verbose_name='Đơn vị quản lý cấp trên')),
            ],
            options={
                'verbose_name': 'Danh mục kho',
                'verbose_name_plural': 'Danh mục kho',
            },
        ),
        migrations.CreateModel(
            name='Phieu_nhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateField(verbose_name='Thời gian nhập')),
                ('quyetdinh', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('success', models.BooleanField(default=False)),
                ('kho_nhap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='import_data', to='qlpt.danh_muc_kho', verbose_name='Kho nhập')),
                ('kho_xuat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='export_data', to='qlpt.danh_muc_kho', verbose_name='Kho xuất')),
                ('nguon_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_nguon_cap', verbose_name='Nguồn cấp')),
            ],
            options={
                'verbose_name': 'Phiếu nhập',
                'verbose_name_plural': 'Phiếu nhập',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='Chi_tiet_phieu_nhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=500, verbose_name='Tên')),
                ('so_luong', models.BigIntegerField(verbose_name='Số lượng')),
                ('nguyen_gia', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Nguyên giá (VNĐ)')),
                ('nam_cap', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Năm cấp')),
                ('hinh_anh', models.FileField(blank=True, null=True, upload_to='static', verbose_name='Hình ảnh')),
                ('file', models.FileField(blank=True, null=True, upload_to='static', verbose_name='File liên quan')),
                ('chung_loai', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.chung_loai', verbose_name='Chủng loại')),
                ('nguon_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qlpt.danh_muc_nguon_cap', verbose_name='Nguồn cấp')),
                ('phieu_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phuong_tiens', to='qlpt.phieu_nhap')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập',
                'verbose_name_plural': 'Chi tiết phiếu nhập',
            },
        ),
        migrations.CreateModel(
            name='Tai_lieu_phuong_tien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên phương tiện')),
                ('chung_loai', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qlpt.chung_loai', verbose_name='Chủng loại')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static', verbose_name='File tài liệu')),
                ('Tai_lieu_phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='qlpt.tai_lieu_phuong_tien')),
            ],
        ),
    ]
