# Generated by Django 6.0 on 2026-01-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0003_danh_muc_nguon_cap_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhuongTien',
            new_name='PhuongTienHuHong',
        ),
    ]
