# Generated by Django 6.0 on 2026-01-08 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0004_rename_phuongtien_phuongtienhuhong'),
    ]

    operations = [
        migrations.AddField(
            model_name='chi_tiet_phieu_nhap',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='qlpt.chi_tiet_phieu_nhap', verbose_name='phuong_tien_kem_theo'),
        ),
    ]
