# Generated by Django 6.0 on 2026-01-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0005_chi_tiet_phieu_nhap_parent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='danh_muc_kho',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AddField(
            model_name='danh_muc_kho',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phuong_tien_kem_theo', to='qlpt.chi_tiet_phieu_nhap', verbose_name='Kèm theo phương tiện'),
        ),
    ]
