# Generated by Django 6.0 on 2026-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0006_danh_muc_kho_latitude_danh_muc_kho_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danh_muc_kho',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='danh_muc_kho',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Kinh độ'),
        ),
    ]
