# Generated by Django 6.0 on 2026-01-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0008_alter_danh_muc_kho_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qlpt.chi_tiet_phieu_nhap', verbose_name='Kèm theo phương tiện'),
        ),
    ]
