# Generated by Django 6.0 on 2026-01-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0009_alter_chi_tiet_phieu_nhap_parent_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danh_muc_kho',
            options={'ordering': ['id'], 'verbose_name': 'Danh mục kho', 'verbose_name_plural': 'Danh mục kho'},
        ),
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kemtheo', to='qlpt.chi_tiet_phieu_nhap', verbose_name='Kèm theo phương tiện'),
        ),
    ]
