# Generated by Django 6.0 on 2026-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0010_alter_danh_muc_kho_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='ten',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Tên'),
        ),
    ]
