# Generated by Django 6.0 on 2026-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpt', '0011_alter_chi_tiet_phieu_nhap_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_phieu_nhap',
            name='ten',
            field=models.CharField(max_length=500, verbose_name='Tên'),
        ),
    ]
