# Generated by Django 3.2.4 on 2024-07-24 02:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bo_phan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Bộ phận',
                'verbose_name_plural': 'Bộ phận',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cap_bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cấp bậc',
                'verbose_name_plural': 'Cấp bậc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='chuc_vu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chức vụ',
                'verbose_name_plural': 'Chức vụ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='thong_tin_ca_nhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/images/upload/')),
                ('ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('que_quan', models.CharField(blank=True, max_length=500, null=True, verbose_name='Quê quán')),
                ('ho_khau', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hộ khẩu')),
                ('sdt', models.CharField(blank=True, max_length=10, null=True, verbose_name='Số điện thoại')),
                ('trinh_do_chinh_tri', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trình độ chính trị')),
                ('trinh_do_chuyen_mon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trình độ chuyên môn')),
                ('ngay_vao_nganh', models.DateField(blank=True, null=True, verbose_name='Ngày vào ngành')),
                ('nam_nhan_cong_tac', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2024)], verbose_name='Năm nhận công tác')),
                ('nam_nghi_cong_tac', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2024)], verbose_name='Năm nghỉ/chuyển công tác/xuất ngũ')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('ghi_chu', models.CharField(blank=True, max_length=500, null=True, verbose_name='Thông tin bổ sung')),
                ('cap_bac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cap_bac', verbose_name='Cấp bậc')),
                ('chuc_vu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.chuc_vu', verbose_name='chức vụ')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userset', to='user.bo_phan', verbose_name='Bộ phận')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin cán bộ, chiến sĩ',
                'verbose_name_plural': 'Thông tin cán bộ, chiến sĩ',
                'ordering': ['chuc_vu', 'cap_bac', 'ngay_sinh'],
            },
        ),
    ]
