# Generated by Django 6.0 on 2026-01-03 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thong_tin_ca_nhan',
            name='nam_nghi_cong_tac',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)], verbose_name='Năm nghỉ/chuyển công tác/xuất ngũ'),
        ),
    ]
